# fly.toml app configuration file generated for wdcc-passport on 2024-02-07T22:12:25+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'react-template-staging'
primary_region = 'syd'

[build]
  # dockerfile contains build time non-sensitive env vars
  dockerfile = "Dockerfile.staging"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024